services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=MyStrongPassword123!
      - plugins.security.ssl.http.enabled=false
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: dashboards
    depends_on:
      - opensearch
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=MyStrongPassword123!
      - OPENSEARCH_SECURITY_DASHBOARDS_ADMIN_USERNAME=admin
      - OPENSEARCH_SECURITY_DASHBOARDS_ADMIN_PASSWORD=MyStrongPassword123!
    ports:
      - "5601:5601"

  opensearch-seed:
    image: curlimages/curl:latest
    depends_on:
      - opensearch
    volumes:
      - ./seed:/seed
    entrypoint: ["/bin/sh", "/seed/local_seed.sh"]

volumes:
  opensearch-data:
