spring.application.name=lab-api

# local open search connection configuration
opensearch.host=localhost
opensearch.port=9200
opensearch.scheme=http

# game service configuration
game-service.mtg-game-entries-index-name=mtg-game-entries